[supervisord]
nodaemon=true

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autorestart=true
stdout_logfile=/var/log/nginx/access.log
stderr_logfile=/var/log/nginx/error.log

[program:backend]
command=java -jar /app/backend/app.jar
directory=/app/backend
autorestart=true
stdout_logfile=/var/log/backend.log
stderr_logfile=/var/log/backend_err.log

[program:ai]
command=python3 /app/ai/app.py
directory=/app/ai
autorestart=true
stdout_logfile=/var/log/ai.log
stderr_logfile=/var/log/ai_err.log
